2025-01-09 04:45:56,971 - src.utils.queue.rabbit_queue - ERROR - Error declaring queue claude: 'RabbitQueue' object has no attribute 'channel'
2025-01-09 04:45:56,971 - src.utils.queue.rabbit_queue - ERROR - Error publishing message to claude: 'RabbitQueue' object has no attribute 'channel'
2025-01-09 04:47:29,211 - src.utils.queue.rabbit_queue - ERROR - Error publishing message to chat_gpt_o1: 'coroutine' object has no attribute 'channel'
2025-01-09 04:48:42,935 - src.utils.queue.rabbit_queue - ERROR - Error publishing message to chat_gpt_o1: Object of type Message is not JSON serializable
2025-01-09 05:58:08,050 - src.utils.queue.rabbit_queue - ERROR - Error setting up consumer for claude: PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'claude' in vhost '/': received none but current is the value '10' of type 'byte'
2025-01-09 05:58:08,050 - src.utils.queue.worker - ERROR - Error starting parsing worker: PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'claude' in vhost '/': received none but current is the value '10' of type 'byte'
2025-01-09 06:01:45,420 - src.utils.queue.rabbit_queue - ERROR - Error setting up consumer for claude: 'NoneType' object has no attribute 'consume'
2025-01-09 06:01:45,420 - src.utils.queue.worker - ERROR - Error starting parsing worker: 'NoneType' object has no attribute 'consume'
2025-01-09 06:07:28,100 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'coroutine' object has no attribute 'content'
2025-01-09 06:07:28,100 - src.utils.queue.rabbit_queue - ERROR - Error processing message: 'coroutine' object has no attribute 'content'
2025-01-09 06:07:36,347 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'coroutine' object has no attribute 'content'
2025-01-09 06:07:36,347 - src.utils.queue.rabbit_queue - ERROR - Error processing message: 'coroutine' object has no attribute 'content'
2025-01-09 06:12:55,018 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}
2025-01-09 06:16:42,236 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: Connection error.
2025-01-09 06:16:53,907 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: Connection error.
2025-01-09 06:17:21,702 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}
2025-01-09 06:23:18,064 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'list' object has no attribute 'text'
2025-01-09 07:14:16,799 - src.scripts.antropic.claude_gpt - ERROR - Failed to send message: 'TextBlock' object is not subscriptable
2025-01-09 07:14:16,800 - src.utils.queue.rabbit_queue - ERROR - Error processing message: 'TextBlock' object is not subscriptable
2025-01-09 07:14:16,800 - src.utils.queue.rabbit_queue - ERROR - Error processing message: 'TextBlock' object is not subscriptable
2025-01-09 07:26:38,914 - src.scripts.chat_gpt.chat_gpt_o1 - ERROR - Ошибка при отправке сообщения: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2025-01-09 07:26:38,914 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2025-01-09 07:26:52,702 - src.scripts.chat_gpt.chat_gpt_o1 - ERROR - Ошибка при отправке сообщения: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2025-01-09 07:26:52,702 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2025-01-09 07:26:52,702 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2025-01-09 07:26:52,730 - src.utils.queue.rabbit_queue - ERROR - Error publishing message to chat_gpt_o1_errors: 'int' object has no attribute 'message_id'
2025-01-09 07:26:52,730 - src.utils.queue.rabbit_queue - ERROR - Error publishing message to chat_gpt_o1_errors: 'int' object has no attribute 'message_id'
2025-01-09 07:30:07,539 - src.scripts.chat_gpt.chat_gpt_o1 - ERROR - Ошибка при отправке сообщения: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-01-09 07:30:07,544 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-01-09 07:30:07,544 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-01-09 07:31:18,832 - src.scripts.chat_gpt.chat_gpt_o1 - ERROR - Ошибка при отправке сообщения: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-01-09 07:31:18,833 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
2025-01-09 07:31:18,833 - src.utils.queue.rabbit_queue - ERROR - Error processing message: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
